### ISSUE TITLE
TypeError: 'long' object is not iterable / TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by pvita** [Vildnex/facebook_grab_posts#1]
Hi there,
I'm receiving these errors with Python 2.7, 3.5 and 3.6.
I have installed all the requirements but I can't launch the script.
Can you help me?

Best regards
P

_> Traceback (most recent call last):
>   File "C:\Users\utente\Downloads\facebook_grab_posts-master\facebook_grab_posts-master\grab_group_data.py", line 93, in <module>
>     run()
>   File "C:\Users\utente\Downloads\facebook_grab_posts-master\facebook_grab_posts-master\grab_group_data.py", line 86, in run
>     facebook_groups = get_html_group_pages(session, FacebookDATA['FACEBOOK_ID'], FacebookDATA['FACEBOOK_PW'])
>   File "C:\Users\utente\Downloads\facebook_grab_posts-master\facebook_grab_posts-master\grab_group_data.py", line 25, in get_html_group_pages
>     for group in FacebookDATA['GROUPS']:
> TypeError: 'long' object is not iterable_

**Comment by Vildnex** [comment]
Hmmm, ok it looks suspicious. For the moment I'm not able to check it but I will take a look and try to fix it in like 4 to 5 days. Could to tell me what's your operating system? Also did you setup the username, password and groups from where do you want to get data in config.yml?

**Comment by pvita** [comment]
My operating system is Windows 10 Home - 64 Bit.
Yes i did the setup as you described in the readme file and the group i tryed to scrape is public.
